### ISSUE TITLE
building bug: Chart.js not found

### ISSUE THREAD

**Issue by gmarciani** [akveo/blur-admin#54]
The following error has been raised during theme building: Chart.js seems not to be installed, but actually it is inside app/vendors. 
Any suggestion to solve it, and proceed with the theme building?
After I cloned the repo, I run 
```
npm install
bower install
gulp build
```
and i get the following:
```
gulp-inject 1 files into 404.html.
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: Error: Chart.js is not installed. Try running "bower install".
    at /blur-admin/node_modules/wiredep/wiredep.js:30:56
    at /blur-admin/node_modules/wiredep/lib/detect-dependencies.js:145:29
    at forOwn (/blur-admin/node_modules/wiredep/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.forEach (/blur-admin/node_modules/wiredep/node_modules/lodash/dist/lodash.js:3303:9)
    at detectDependencies (/blur-admin/node_modules/wiredep/lib/detect-dependencies.js:34:7)
    at wiredep (/blur-admin/node_modules/wiredep/wiredep.js:70:39)
    at DestroyableTransform._transform (/blur-admin/node_modules/wiredep/wiredep.js:135:34)
    at DestroyableTransform.Transform._read (/blur-admin/node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/blur-admin/node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/blur-admin/node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
```

**Comment by Fotso** [comment]
Same problem, I haven't found a solution yet.

**Comment by vazh** [comment]
have you installed gulp-cli ?
`npm i -g gulp-cli`

**Comment by Fotso** [comment]
Yes I did and the problem still the same.

**Comment by vazh** [comment]
Delete node_modules folder and then run npm install.

**Comment by Fotso** [comment]
Deleting the folder then running the command  npm install conduct to the same result...

**Comment by lugovsky** [comment]
@Fotso have you found a solution? What OS are you using?

**Comment by Fotso** [comment]
@lugovsky I haven't found a solution but I switched with the ng2-admin project, who work like a charm.
I am using windows 8.

**Comment by rom4ik932** [comment]
I have the same problem.

**Comment by rom4ik932** [comment]
I use windows 10

**Comment by k4ren** [comment]
had the same problem in win7 x64, I did the following:
-Delete node_modules folder
- `npm install` 
this gives error in node_gyp, and 
- `npm install -g node-gyp` specifications for win -->  [https://github.com/nodejs/node-gyp/blob/master/README.md] (node)
-and in the bower.json add the next line
- `"resolutions": { "angular": "~1.3.x" }`, this solves the problem with the version of angularjs
- `bower install`

if you run gulp error , look here #90

**Comment by yantrab** [comment]
same problem... 
win 10.

i no understand how k4ren fix it.

**Comment by nnixaa** [comment]
Hey guys, as the issue is resolved I'm closing it now, let us know if you have any questions.

**Comment by Ashu-FT** [comment]
I'm still having the same problem 


The following error has been raised during theme building: Chart.js seems not to be installed, but actually it is inside app/vendors.
Any suggestion to solve it, and proceed with the theme building?
After I cloned the repo, I run

npm install
bower install
gulp build

and i get the following:

gulp-inject 1 files into 404.html.
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: Error: Chart.js is not installed. Try running "bower install".
    at /blur-admin/node_modules/wiredep/wiredep.js:30:56
    at /blur-admin/node_modules/wiredep/lib/detect-dependencies.js:145:29
    at forOwn (/blur-admin/node_modules/wiredep/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.forEach (/blur-admin/node_modules/wiredep/node_modules/lodash/dist/lodash.js:3303:9)
    at detectDependencies (/blur-admin/node_modules/wiredep/lib/detect-dependencies.js:34:7)
    at wiredep (/blur-admin/node_modules/wiredep/wiredep.js:70:39)
    at DestroyableTransform._transform (/blur-admin/node_modules/wiredep/wiredep.js:135:34)
    at DestroyableTransform.Transform._read (/blur-admin/node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/blur-admin/node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/blur-admin/node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)


I'm running my project on Linux centOS
